kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gceme
      role: backend
      env: production
  template:
    metadata:
      name: backend
      labels:
        app: gceme
        role: backend
        env: production
    spec:
      containers:
        - name: backend
          image: corelab/gceme:1.0.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          command: ["sh", "-c", "app -port=8080"]
          ports:
            - name: backend
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: gceme-backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    role: backend
    app: gceme
